### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by andrejsimko-accenture** [synacktiv/Prox-Ez#1]
Hi,
I need to test a website which has NTLM authentication. With ZAP, or directly from Firefox/Chrome it works, but with Burp Suite in the middle it doesn't (even after disabling HTTP/2). I've hoped your extension would help there as you probably faced the same problems, but all I get is a failure stack trace:
````
─# python3 proxy.py -du myuser@domain.com -dp myPassword
INFO:Proxy:Proxy socket bound, listening on 127.0.0.1:3128.
INFO:Proxy:Got connection from 127.0.0.1:33172.
/opt/Prox-Ez/proxy.py:703: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  self.context = ssl.SSLContext(ssl.PROTOCOL_TLS)
Process Process-1:
Traceback (most recent call last):
  File "/opt/Prox-Ez/venv/lib/python3.10/site-packages/impacket/ntlm.py", line 617, in getNTLMSSPType3
    domain.encode('utf-16le')
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Prox-Ez/proxy.py", line 1012, in handle_connection
    authorization_header = prx2srv_hdler.check_auth(srv_resp, cur_creds, self.lmhash, self.nthash)
  File "/opt/Prox-Ez/proxy.py", line 590, in check_auth
    new_token = self.gen_ntlm_auth(creds,lmhash,nthash)
  File "/opt/Prox-Ez/proxy.py", line 527, in gen_ntlm_auth
    auth, exported_session_key = getNTLMSSPType3(self.ntlm_auth["negotiate"], self.ntlm_auth["challenge"], creds["username"], creds["password"] , creds["domain"], lmhash, nthash)
  File "/opt/Prox-Ez/venv/lib/python3.10/site-packages/impacket/ntlm.py", line 619, in getNTLMSSPType3
    domain = user.decode(encoding)
AttributeError: 'str' object has no attribute 'decode'

````

When running testssl.sh against the server in scope, I get following:
````
Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
-----------------------------------------------------------------------------------------------------------------------------
 xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH 384   AESGCM      256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384              
 x9f     DHE-RSA-AES256-GCM-SHA384         DH 2048    AESGCM      256      TLS_DHE_RSA_WITH_AES_256_GCM_SHA384                
 x9d     AES256-GCM-SHA384                 RSA        AESGCM      256      TLS_RSA_WITH_AES_256_GCM_SHA384                    
 xc02f   ECDHE-RSA-AES128-GCM-SHA256       ECDH 253   AESGCM      128      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256              
 x9e     DHE-RSA-AES128-GCM-SHA256         DH 2048    AESGCM      128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256                
 x9c     AES128-GCM-SHA256                 RSA        AESGCM      128      TLS_RSA_WITH_AES_128_GCM_SHA256                    
 x3c     AES128-SHA256                     RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA256  
````

I've tried to use username as `sub.domain.com\\username` as well as `username@sub.domain.com` but the error is the same. Note that the above occurs when I refresh Firefox set to 3128 (proxy.py) as well as 8080 (Burp with upstream proxy of 3128).

When I try just to trigger a repeater request, I get lesser error:
````
INFO:Proxy:Proxy socket bound, listening on 127.0.0.1:3128.
INFO:Proxy:Got connection from 127.0.0.1:50486.
/opt/Prox-Ez/proxy.py:703: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  self.context = ssl.SSLContext(ssl.PROTOCOL_TLS)
````
but I still get `HTTP/1.1 401 Unauthorized` back so I'm not authenticated.

Any ideas how to make it work? Thanks! :) It appears to be wonderful tool, just what I need! :)

**Comment by b1two-syn** [comment]
Sorry for the delay, we do not have notifications from this Github repo.

I don't think that your problem lies in improper TLS configuration (it is just a warning). However, I will look into this, so that we get rid of it.

On another note, these errors are typical when the username and domain are not correctly specified. You are right, you have to specify the username and domain as `domain\\username` or `'domain\username'` (note the additional single quotes). I am currently reworking the way to specify credentials in order to be closer to impacket's syntax, which is the "standard" nowadays.
It may solve your problem, but I guess it will come too late for your test :/

I'll update this issue, when the edit has been made.

**Comment by b1two-syn** [comment]
Credentials are now provided in a new way (since 1a8722ed98818c18f5b1b977cf4872495225afde, but use the last version tho).
I will close this, feel free to comment if you still encounter such issue.
